db:
  host: 0.0.0.0
  port: 5432
  schema: public
  user: postgres
  password: password
  name: test
messages_consumer:
  brokers:
    - 0.0.0.0:9092
  topic: sample
  group_id: sample_group_1
messages_producer:
  brokers:
    - 0.0.0.0:9092
  topic: sample
